/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUI.java
 *
 * Created on 2015.10.22., 23:10:59
 */
package pricecalc;

import java.awt.Dimension;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import pricecalc.utils.CSVFileHandler;
import pricecalc.utils.CSVRecord;

/**
 *
 * @author arsene
 */
public class GUI extends javax.swing.JFrame implements UI{

    /** Creates new form GUI */
    public GUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPaneMain = new javax.swing.JSplitPane();
        jPanelDB = new javax.swing.JPanel();
        jToolBarDB = new javax.swing.JToolBar();
        jTannedPaneDB = new javax.swing.JTabbedPane();
        jScrollPaneBasePriceRatio = new javax.swing.JScrollPane();
        jTableBasePriceRatio = new javax.swing.JTable();
        jScrollPaneIntervals = new javax.swing.JScrollPane();
        jTableIntervals = new javax.swing.JTable();
        jScrollPaneServiceTypes = new javax.swing.JScrollPane();
        jTableServiceTypes = new javax.swing.JTable();
        jScrollPaneApClasses = new javax.swing.JScrollPane();
        jTableApClasses = new javax.swing.JTable();
        jScrollPaneAPs = new javax.swing.JScrollPane();
        jTableAPs = new javax.swing.JTable();
        jPanelContractsResults = new javax.swing.JPanel();
        jToolBarContractsResults = new javax.swing.JToolBar();
        jTabbedPaneContractsResults = new javax.swing.JTabbedPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ár kalkulátor");

        jSplitPaneMain.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jToolBarDB.setFloatable(false);
        jToolBarDB.setRollover(true);

        jTableBasePriceRatio.setModel(tableModelBasePriceRatio);
        jScrollPaneBasePriceRatio.setViewportView(jTableBasePriceRatio);

        jTannedPaneDB.addTab("Alap ár százalék", jScrollPaneBasePriceRatio);

        jTableIntervals.setModel(tableModelBasePriceRatio);
        jScrollPaneIntervals.setViewportView(jTableIntervals);

        jTannedPaneDB.addTab("Időszakok", jScrollPaneIntervals);

        jTableServiceTypes.setModel(tableModelBasePriceRatio);
        jScrollPaneServiceTypes.setViewportView(jTableServiceTypes);

        jTannedPaneDB.addTab("Szolgáltatás típusok", jScrollPaneServiceTypes);

        jTableApClasses.setModel(tableModelBasePriceRatio);
        jScrollPaneApClasses.setViewportView(jTableApClasses);

        jTannedPaneDB.addTab("Hozzáférési pont típusok", jScrollPaneApClasses);

        jTableAPs.setModel(tableModelBasePriceRatio);
        jScrollPaneAPs.setViewportView(jTableAPs);

        jTannedPaneDB.addTab("Hozzáférési pontok", jScrollPaneAPs);

        javax.swing.GroupLayout jPanelDBLayout = new javax.swing.GroupLayout(jPanelDB);
        jPanelDB.setLayout(jPanelDBLayout);
        jPanelDBLayout.setHorizontalGroup(
            jPanelDBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBarDB, javax.swing.GroupLayout.DEFAULT_SIZE, 919, Short.MAX_VALUE)
            .addComponent(jTannedPaneDB, javax.swing.GroupLayout.DEFAULT_SIZE, 919, Short.MAX_VALUE)
        );
        jPanelDBLayout.setVerticalGroup(
            jPanelDBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDBLayout.createSequentialGroup()
                .addComponent(jToolBarDB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTannedPaneDB, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
        );

        jTannedPaneDB.getAccessibleContext().setAccessibleName("TabDB");

        jSplitPaneMain.setLeftComponent(jPanelDB);

        jToolBarContractsResults.setFloatable(false);
        jToolBarContractsResults.setRollover(true);

        javax.swing.GroupLayout jPanelContractsResultsLayout = new javax.swing.GroupLayout(jPanelContractsResults);
        jPanelContractsResults.setLayout(jPanelContractsResultsLayout);
        jPanelContractsResultsLayout.setHorizontalGroup(
            jPanelContractsResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBarContractsResults, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 919, Short.MAX_VALUE)
            .addComponent(jTabbedPaneContractsResults, javax.swing.GroupLayout.DEFAULT_SIZE, 919, Short.MAX_VALUE)
        );
        jPanelContractsResultsLayout.setVerticalGroup(
            jPanelContractsResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContractsResultsLayout.createSequentialGroup()
                .addComponent(jToolBarContractsResults, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPaneContractsResults, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE))
        );

        jSplitPaneMain.setRightComponent(jPanelContractsResults);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPaneMain, javax.swing.GroupLayout.DEFAULT_SIZE, 921, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPaneMain, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JPanel jPanelContractsResults;
    private javax.swing.JPanel jPanelDB;
    private javax.swing.JScrollPane jScrollPaneAPs;
    private javax.swing.JScrollPane jScrollPaneApClasses;
    private javax.swing.JScrollPane jScrollPaneBasePriceRatio;
    private javax.swing.JScrollPane jScrollPaneIntervals;
    private javax.swing.JScrollPane jScrollPaneServiceTypes;
    private javax.swing.JSplitPane jSplitPaneMain;
    private javax.swing.JTabbedPane jTabbedPaneContractsResults;
    private javax.swing.JTable jTableAPs;
    private javax.swing.JTable jTableApClasses;
    private javax.swing.JTable jTableBasePriceRatio;
    private javax.swing.JTable jTableIntervals;
    private javax.swing.JTable jTableServiceTypes;
    private javax.swing.JTabbedPane jTannedPaneDB;
    private javax.swing.JToolBar jToolBarContractsResults;
    private javax.swing.JToolBar jToolBarDB;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

    private Dimension jOptionPaneDim = new Dimension(420, 180);
    
    private DefaultTableModel tableModelBasePriceRatio = new DefaultTableModel(
            new String[]{"valami"}, 0);
    
    @Override
    public void start() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        javax.swing.UIManager.put("OptionPane.cancelButtonText", "Mégsem");
        javax.swing.UIManager.put("OptionPane.noButtonText", "Nem");
        javax.swing.UIManager.put("OptionPane.okButtonText", "Rendben");
        javax.swing.UIManager.put("OptionPane.yesButtonText", "Igen");
        
        SwingUtilities.updateComponentTreeUI(this);
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            @Override
            public void run() {
                setVisible(true);
            }
        });
    }

    class CSVTableModel extends AbstractTableModel{
        private final CSVFileHandler handler;
        private List<CSVRecord> rows;
        
        public CSVTableModel(CSVFileHandler handler, List<CSVRecord> rows){
            this.handler = handler;
            this.rows = rows;
        }

        @Override
        public int getRowCount() {
            return rows.size();
        }

        @Override
        public int getColumnCount() {
            return handler.getHeader().size();
        }
        
        @Override
        public String getColumnName(int columnIndex) {
            return handler.getHeaderToStringArray()[columnIndex];
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            return rows.get(rowIndex).toStringField(columnIndex);
        }
    }
    
    @Override
    public void showBasePriceRatio(CSVFileHandler handler, List<CSVRecord> rows) {
        jTableBasePriceRatio.setModel(new CSVTableModel(handler, rows));
    }
    
    
    @Override
    public void showIntervals(CSVFileHandler handler, List<CSVRecord> rows) {
        jTableIntervals.setModel(new CSVTableModel(handler, rows));
    }

    @Override
    public void showServiceTypes(CSVFileHandler handler, List<CSVRecord> rows) {
        jTableServiceTypes.setModel(new CSVTableModel(handler, rows));
    }

    @Override
    public void showApClasses(CSVFileHandler handler, List<CSVRecord> rows) {
        jTableApClasses.setModel(new CSVTableModel(handler, rows));
    }

    @Override
    public void showAPs(CSVFileHandler handler, List<CSVRecord> rows) {
        jTableAPs.setModel(new CSVTableModel(handler, rows));
    }
    
    @Override
    public void showContract(final CSVFileHandler handler, final List<CSVRecord> rows, PriceCalc calculator) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                JSplitPane jSplitPaneContractResult = new JSplitPane();
                JScrollPane jScrollPaneContract = new JScrollPane();
                JTable jTableContract = new JTable();
                JScrollPane jScrollPaneResult = new JScrollPane();
                JTable jTableResult = new JTable();

                String name = handler.getFile().getName();
                int extPos = name.lastIndexOf(".");

                if (extPos != -1) {
                    name = name.substring(0, extPos);
                }

                jTableContract.setModel(new CSVTableModel(handler, rows));
                
                jScrollPaneContract.setViewportView(jTableContract);
                jScrollPaneResult.setViewportView(jTableResult);

                jSplitPaneContractResult.setDividerLocation(95);
                jSplitPaneContractResult.setOrientation(JSplitPane.VERTICAL_SPLIT);

                jSplitPaneContractResult.setTopComponent(jScrollPaneContract);
                jSplitPaneContractResult.setBottomComponent(jScrollPaneResult);


                jTabbedPaneContractsResults.addTab(name, jSplitPaneContractResult);
            }
        });
        
    }
    
    @Override
    public void showError(String msg) { 
        JOptionPane pane = new JOptionPane("<html><body><p style='width: 250px;'>"
                + msg + "</p></body></html>", JOptionPane.ERROR_MESSAGE);
        JDialog dialog = pane.createDialog("Hiba történt!");
        
        dialog.setSize(jOptionPaneDim);
        dialog.setVisible(true);
        dialog.dispose();
    }

    @Override
    public void showMessage(String msg) {
        JOptionPane pane = new JOptionPane("<html><body><p style='width: 250px;'>"
                + msg + "</p></body></html>", JOptionPane.INFORMATION_MESSAGE);
        JDialog dialog = pane.createDialog("Üzenet");
        
        dialog.setSize(jOptionPaneDim);
        dialog.setVisible(true);
        dialog.dispose();
    }

    @Override
    public boolean askYesNo(String msg) {
        JOptionPane pane = new JOptionPane("<html><body><p style='width: 250px;'>"
                + msg + "</p></body></html>", JOptionPane.QUESTION_MESSAGE,
                JOptionPane.YES_NO_OPTION);
        JDialog dialog;
        do{
            dialog = pane.createDialog("Mi legyen a döntés?");

            dialog.setSize(jOptionPaneDim);
            dialog.setVisible(true);
            dialog.dispose();

            try {
                return (int) pane.getValue() == JOptionPane.YES_OPTION;
            } catch (NullPointerException ignore) {
            }
        } while(true);
    }
}
